###

# Also can be named with `.http` extension
# Reference - https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#

###

GET http://localhost:8080/api

###

GET http://localhost:8080/api/2

###

GET http://localhost:8080/actuator/info

###
