server:
  port: 8080

spring:
  main:
    lazy-initialization: true # Global Lazy Bean Initialization - Enabled by default in spring-boot 2.2
  application:
    name: my-spring-boot-playground
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    continue-on-error: false
  jpa:
    hibernate:
      # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-initialize-a-database-using-hibernate
      # Possible values - none, validate, update, create, and create-drop
      ddl-auto: update # Suitable for production
    properties:
      hibernate:
#        default_schema: appschema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.encoding: @project.build.sourceEncoding@
  application.name: ${spring.application.name}
  application.artifact: @project.artifactId@
  application.version: @project.version@
  spring.boot.version: @spring-boot.version@

# Expose all Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true

endpoint:
  health:
    show-details: always

logging.level:
  com.shaunthomas999: debug

app:
  test-property-1: test1
  test-property-2: test2

feature:
  boolean-flag:
    enabled: true
