# Ref: List of common configurations - https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# Ref: Externalize configurations - https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
server:
  port: 8400

spring:
  main:
    lazy-initialization: true # Global Lazy Bean Initialization - Enabled by default in spring-boot 2.2
  application:
    name: my-spring-boot-playground
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
  jpa:
    hibernate:
      # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-initialize-a-database-using-hibernate
      # Possible values - none, validate, update, create, and create-drop
      # Suitable for production - validate
      ddl-auto: update
    properties:
      hibernate:
#        default_schema: appschema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      continue-on-error: false

# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
#  application.encoding: @project.build.sourceEncoding@
  application.name: ${spring.application.name}
#  application.artifact: @project.artifactId@
#  application.version: @project.version@
#  spring.boot.version: @spring-boot.version@

# Expose all Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true

endpoint:
  health:
    show-details: always

logging.level:
  com.shaunthomas999: debug

app:
  test-property-1: test1
  test-property-2: test2

feature:
  boolean-flag:
    enabled: true
